### ISSUE TITLE
Support Python 3.5

### ISSUE THREAD

**Issue by DaveDeCaprio** [closedloop-ai/cv19index#11]
Currently we only support Python 3.6 because of the type hinting that we have.  We should check whether there is a backwards compatible way to support this in Python 3.5.  Otherwise we should look at whether we should remove those hints to increase the availability of the code.

**Comment by wgillett** [comment]
Hi - I'm looking to help out during the pandemic and this project caught my eye.
Puzzled by this ticket because type hints were [introduced in Python 3.5](https://realpython.com/lessons/type-hinting/) and work fine with this version? On the flip side, the code uses a bunch of f-strings and that feature wasn't added until 3.6. I did find a [backport of f-strings](https://github.com/asottile/future-fstrings) , that might be an option. How much value is there in supporting Python 3.5?

**Comment by DaveDeCaprio** [comment]
We just had one person at the start who ran into an issue and they upgraded.  I'd say there isn't a ton of value here.  The biggest outstanding item we have now is BlueButton support.  https://bluebutton.cms.gov/developers/#overview
This would enable medicare members to directly put their own data into the model.

This is a bit of a bigger ticket item though.

**Comment by wgillett** [comment]
@DaveDeCaprio Given small value for Python 3.5 support, suggest closing this ticket and opening one for BlueButton support.
